const TRIP = {
  title: "제주 여행 코스",
  dates: "2026.7.8 (수) ~ 7.13 (월)",
  flight: {
    outbound: { date: "7/8 (수)", time: "13:45", route: "김포 → 제주" },
    inbound: { date: "7/13 (월)", time: "20:50", route: "제주 → 김포" },
  },
  rental: {
    name: "제주OK렌터카",
    time: "15:00 인수",
    address: "제주시 용문로 64",
    mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
  },
  stay: {
    name: "제주 뜨리바다",
    nights: 5,
    address: "서귀포시 남원읍 태위로510번길 31-16",
    mapUrl: "https://map.kakao.com/link/search/제주%20뜨리바다",
  },
  mapLinks: {
    kakao: { label: "카카오맵 (전체)", url: "https://kko.to/dVTagxHHZX" },
    naverFood: { label: "네이버 먹거리", url: "https://naver.me/5wrj0ShJ" },
    naverPlay: { label: "네이버 놀거리", url: "https://naver.me/Gi0OR11p" },
    naverDessert: { label: "네이버 디저트", url: "https://naver.me/GahyuPIM" },
  },
};

const DAYS = [
  {
    id: "day1",
    label: "Day 1",
    date: "7/8 (수)",
    theme: "도착 · 아베베 · 숙소",
    summary: "렌트 인수 → 점심 → 아베베 → 체크인 → 해녀촌 저녁",
    swim: false,
    stops: [
      {
        time: "13:45",
        name: "제주공항 도착",
        type: "이동",
        note: "김포 13:45 출발편",
        source: null,
      },
      {
        time: "15:00",
        name: "제주OK렌터카",
        type: "렌트카",
        address: "제주시 용문로 64",
        note: "공항 셔틀 약 10~15분 간격",
        mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
        source: null,
      },
      {
        time: "15:30",
        name: "해맞이쉼터",
        type: "먹거리",
        address: "제주",
        note: "점심(리스트 내 식당)",
        mapUrl: "https://map.naver.com/v5/search/해맞이쉼터%20제주",
        source: "naver",
      },
      {
        time: "16:00",
        name: "아베베 베이커리 제주",
        type: "디저트",
        address: "제주시 일도일동 1136-2",
        note: "필수 방문! 오픈 시간 확인 후 방문",
        highlight: true,
        mapUrl: "https://map.naver.com/v5/search/아베베%20베이커리%20제주",
        source: "naver",
      },
      {
        time: "17:30",
        name: "제주 뜨리바다",
        type: "숙소",
        address: "서귀포시 남원읍 태위로510번길 31-16",
        note: "5박 숙박 · 체크인",
        mapUrl: "https://map.kakao.com/link/search/제주%20뜨리바다",
        source: null,
      },
      {
        time: "19:00",
        name: "어등포해녀촌",
        type: "먹거리",
        address: "제주시 이도일동 1782-1",
        note: "저녁 · 해녀 음식",
        mapUrl: "https://map.naver.com/v5/search/어등포해녀촌",
        source: "naver",
      },
    ],
  },
  {
    id: "day2",
    label: "Day 2",
    date: "7/9 (목)",
    theme: "북동 · 함덕 · 조천",
    summary: "수영 → 점심(12) → 조천 북카페 → 카페 → 저녁(16) → 일몰 → 디저트",
    swim: true,
    swimSpot: "함덕해수욕장",
    stops: [
      {
        time: "09:30",
        name: "함덕해수욕장",
        type: "수영",
        address: "제주시 조천읍 함덕리",
        note: "아침 수영",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/함덕해수욕장",
        source: "naver",
      },
      {
        time: "12:00",
        name: "통일가든",
        type: "먹거리",
        address: "조천읍 조와로 14",
        note: "점심(12)",
        mapUrl: "https://map.kakao.com/link/search/통일가든%20제주",
        source: "both",
      },
      {
        time: "13:00",
        name: "만춘서점",
        type: "놀거리",
        address: "조천읍 함덕로 9",
        note: "함덕 독립서점",
        mapUrl: "https://map.kakao.com/link/search/만춘서점%20제주",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "바라나시책골목",
        type: "놀거리",
        address: "조천읍 일주동로 952-5",
        note: "함덕·조천 일대 북카페",
        mapUrl: "https://map.kakao.com/link/search/바라나시책골목",
        source: "kakao",
      },
      {
        time: "15:00",
        name: "델문도",
        type: "카페",
        address: "조천읍 조함해안로 519-10",
        note: "카페(디저트/커피 1회차)",
        mapUrl: "https://map.kakao.com/link/search/델문도%20제주",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "매우릉쭈꾸미",
        type: "먹거리",
        address: "조천읍 함덕16길 11",
        note: "저녁(16)",
        mapUrl: "https://map.kakao.com/link/search/매우릉쭈꾸미",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "관곶",
        type: "놀거리",
        address: "조천읍 조함해안로 217-1",
        note: "해안 산책",
        mapUrl: "https://map.kakao.com/link/search/관곶",
        source: "kakao",
      },
      {
        time: "19:00",
        name: "글로시말차",
        type: "디저트",
        address: "조천읍 조함해안로 112",
        note: "디저트(2회차) · 관곶 일몰 후",
        mapUrl: "https://map.kakao.com/link/search/글로시말차",
        source: "kakao",
      },
    ],
  },
  {
    id: "day3",
    label: "Day 3",
    date: "7/10 (금)",
    theme: "동부 · 성산 · 구좌",
    summary: "수영 → 점심(12) → 구좌 카페 → 해변 → 저녁(16) → 야식(20)",
    swim: true,
    swimSpot: "세기알해변",
    stops: [
      {
        time: "09:30",
        name: "세기알해변",
        type: "수영",
        address: "구좌읍",
        note: "아침 수영",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/세기알해변",
        source: "kakao",
      },
      {
        time: "12:00",
        name: "몰마농 그대와함께 해물라면 성산본점",
        type: "먹거리",
        address: "성산 일대",
        note: "점심(12)",
        mapUrl: "https://map.naver.com/v5/search/몰마농%20해물라면%20성산",
        source: "naver",
      },
      {
        time: "13:30",
        name: "시타북바 세화해변",
        type: "디저트",
        address: "구좌읍 평대리 3350-13",
        note: "디저트/북카페(1회차) · 세화해변 인근",
        mapUrl: "https://map.naver.com/v5/search/시타북바%20세화해변",
        source: "naver",
      },
      {
        time: "15:00",
        name: "구씨커피로스터스",
        type: "카페",
        address: "구좌읍 구좌로 21",
        note: "카페(2회차) · 세화·평대 일대",
        mapUrl: "https://map.kakao.com/link/search/구씨커피로스터스",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "복자씨연탄구이",
        type: "먹거리",
        address: "성산 일대",
        note: "저녁(16) · 성산 일대",
        mapUrl: "https://map.naver.com/v5/search/복자씨연탄구이%20제주",
        source: "naver",
      },
      {
        time: "17:30",
        name: "행원해변",
        type: "놀거리",
        address: "구좌읍",
        note: "해안 산책 · 구좌 동선",
        mapUrl: "https://map.kakao.com/link/search/행원해변",
        source: "kakao",
      },
      {
        time: "20:00",
        name: "동복리 해녀촌",
        type: "먹거리",
        address: "구좌읍",
        note: "야식(20) · 구좌 동선 유지",
        mapUrl: "https://map.naver.com/v5/search/동복리%20해녀촌%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day4",
    label: "Day 4",
    date: "7/11 (토)",
    theme: "서부 · 판포 · 한림",
    summary: "판포 수영 → 서부 점심 → 한림 카페 → 귀숙로 저녁·야식",
    swim: true,
    swimSpot: "판포포구",
    stops: [
      {
        time: "09:30",
        name: "판포포구",
        type: "수영",
        address: "한경면 판포리",
        note: "아침 수영",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/판포포구",
        source: "kakao",
      },
      {
        time: "12:00",
        name: "번네식당",
        type: "먹거리",
        address: "안덕면 일주서로 1606-10",
        note: "점심(12) · 서부 해안 이동",
        mapUrl: "https://map.kakao.com/link/search/번네식당",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "코삿호다",
        type: "디저트",
        address: "한경면 판포리 2881-3",
        note: "디저트(1회차) · 판포 인근",
        mapUrl: "https://map.kakao.com/link/search/코삿호다",
        source: "both",
      },
      {
        time: "15:30",
        name: "우무",
        type: "디저트",
        address: "한림읍 옹포리 324-3",
        note: "디저트(2회차) · 한림",
        mapUrl: "https://map.naver.com/v5/search/우무%20제주",
        source: "naver",
      },
      {
        time: "16:30",
        name: "KT한림빌딩",
        type: "놀거리",
        address: "한림읍 한림로 630",
        note: "한림 카페거리",
        mapUrl: "https://map.kakao.com/link/search/KT한림빌딩",
        source: "kakao",
      },
      {
        time: "17:00",
        name: "오병장 본점",
        type: "먹거리",
        address: "제주시 벌랑길 8",
        note: "저녁(16) · 숙소 방향 경유",
        mapUrl: "https://map.kakao.com/link/search/오병장%20본점",
        source: "kakao",
      },
      {
        time: "20:00",
        name: "숙성도 제주본점",
        type: "먹거리",
        address: "제주시",
        note: "야식(20) · 제주시 귀숙",
        mapUrl: "https://map.naver.com/v5/search/숙성도%20제주본점",
        source: "naver",
      },
    ],
  },
  {
    id: "day5",
    label: "Day 5",
    date: "7/12 (일)",
    theme: "남부 · 서귀포",
    summary: "점심(12) → 놀거리 → 카페 → 저녁(16) → 카페(2회차) → 야식(20)",
    swim: false,
    stops: [
      {
        time: "12:00",
        name: "미영이네",
        type: "먹거리",
        address: "서귀포시 대정읍 하모리 770-29",
        note: "점심(12)",
        mapUrl: "https://map.naver.com/v5/search/미영이네%20제주",
        source: "naver",
      },
      {
        time: "14:00",
        name: "빈티지농장",
        type: "놀거리",
        address: "서귀포시",
        note: "네이버 놀거리",
        mapUrl: "https://map.naver.com/v5/search/빈티지농장%20제주",
        source: "naver",
      },
      {
        time: "15:00",
        name: "와토커피",
        type: "카페",
        address: "서귀포시 대정읍 동일하모로 238",
        note: "카페(1회차)",
        mapUrl: "https://map.kakao.com/link/search/와토커피",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "앙프르",
        type: "먹거리",
        address: "서귀포시",
        note: "저녁(16)",
        mapUrl: "https://map.naver.com/v5/search/앙프르%20제주",
        source: "naver",
      },
      {
        time: "18:30",
        name: "목장카페 밭디",
        type: "카페",
        address: "제주",
        note: "카페(2회차)",
        mapUrl: "https://map.naver.com/v5/search/목장카페%20밭디%20제주",
        source: "naver",
      },
      {
        time: "20:00",
        name: "충희요리",
        type: "먹거리",
        address: "제주",
        note: "야식(20)",
        mapUrl: "https://map.naver.com/v5/search/충희요리%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day6",
    label: "Day 6",
    date: "7/13 (월)",
    theme: "귀국 · 제주시",
    summary: "점심(12) → 회심 → 기념품 → 저녁(16) → 반납 → 공항",
    swim: false,
    stops: [
      {
        time: "12:00",
        name: "그옛맛",
        type: "먹거리",
        address: "제주시 서사로24길 12",
        note: "점심(12)",
        mapUrl: "https://map.kakao.com/link/search/그옛맛%20제주",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "회심",
        type: "먹거리",
        address: "제주시 아봉로 200",
        note: "일식 소바 · 17시 마감",
        mapUrl: "https://map.kakao.com/link/search/회심%20제주",
        source: "kakao",
      },
      {
        time: "15:00",
        name: "도두슈퍼마켓",
        type: "놀거리",
        address: "제주시 서해안로 135",
        note: "기념품 · 공항 인근",
        mapUrl: "https://map.kakao.com/link/search/도두슈퍼마켓",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "몽탄 제주점",
        type: "먹거리",
        address: "제주",
        note: "저녁(16)",
        mapUrl: "https://map.naver.com/v5/search/몽탄%20제주점%20제주",
        source: "naver",
      },
      {
        time: "19:30",
        name: "제주OK렌터카 반납",
        type: "렌트카",
        address: "제주시 용문로 64",
        note: "셔틀버스로 공항 이동",
        mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
        source: null,
      },
      {
        time: "20:50",
        name: "제주공항 출발",
        type: "이동",
        note: "제주 → 김포",
        source: null,
      },
    ],
  },
];

const KAKAO_JEJU_PLACES = [
  { name: "회심", area: "제주시", source: "kakao" },
  { name: "관곶", area: "조천읍", source: "kakao" },
  { name: "로미뮤직하우스", area: "조천읍", source: "kakao" },
  { name: "글로시말차", area: "조천읍", source: "kakao" },
  { name: "그옛맛", area: "제주시", source: "kakao" },
  { name: "5L2F", area: "조천읍", source: "kakao" },
  { name: "와토커피", area: "대정읍", source: "kakao" },
  { name: "구씨커피로스터스", area: "구좌읍", source: "kakao" },
  { name: "매우릉쭈꾸미", area: "조천읍", source: "kakao" },
  { name: "오병장 본점", area: "제주시", source: "kakao" },
  { name: "번네식당", area: "안덕면", source: "kakao" },
  { name: "행원해변", area: "구좌읍", source: "kakao" },
  { name: "코삿호다", area: "한경면", source: "kakao" },
  { name: "판포포구", area: "한경면", source: "kakao" },
  { name: "통일가든", area: "조천읍", source: "kakao" },
  { name: "바라나시책골목", area: "조천읍", source: "kakao" },
  { name: "KT한림빌딩", area: "한림읍", source: "kakao" },
  { name: "델문도", area: "조천읍", source: "kakao" },
  { name: "만춘서점", area: "조천읍", source: "kakao" },
  { name: "도두슈퍼마켓", area: "제주시", source: "kakao" },
];

const NAVER_SAVED_PLACES = [
  { name: "미영이네", folder: "먹거리" },
  { name: "통일가든", folder: "먹거리" },
  { name: "코삿호다", folder: "먹거리" },
  { name: "어등포해녀촌", folder: "먹거리" },
  { name: "숙성도 제주본점", folder: "먹거리" },
  { name: "함덕해수욕장", folder: "먹거리" },
  { name: "몰마농 그대와함께 해물라면 성산본점", folder: "먹거리" },
  { name: "동복리 해녀촌", folder: "먹거리" },
  { name: "앙프르", folder: "먹거리" },
  { name: "복자씨연탄구이", folder: "먹거리" },
  { name: "충희요리", folder: "먹거리" },
  { name: "몽탄 제주점", folder: "먹거리" },
  { name: "월정리 호랑이네", folder: "먹거리" },
  { name: "해맞이쉼터", folder: "먹거리" },
  { name: "미노아", folder: "먹거리" },
  { name: "서귀포매일올레시장", folder: "먹거리" },
  { name: "빈티지농장", folder: "놀거리" },
  { name: "아베베 베이커리 제주", folder: "디저트" },
  { name: "시타북바 세화해변", folder: "디저트" },
  { name: "풍림다방 커피로스터즈 송당", folder: "디저트" },
  { name: "우무", folder: "디저트" },
];

function isPlaceScheduled(placeName) {
  return DAYS.some((day) =>
    day.stops.some((stop) => {
      if (stop.name === placeName) return true;
      return (
        stop.name.includes(placeName) ||
        placeName.includes(stop.name)
      );
    })
  );
}

function getUnassignedNaverPlaces() {
  return NAVER_SAVED_PLACES.filter((p) => !isPlaceScheduled(p.name));
}
