const TRIP = {
  title: "제주 여행 코스",
  dates: "2026.7.8 (수) ~ 7.13 (월)",
  flight: {
    outbound: { date: "7/8 (수)", time: "13:45", route: "김포 → 제주" },
    inbound: { date: "7/13 (월)", time: "20:50", route: "제주 → 김포" },
  },
  rental: {
    name: "제주OK렌터카",
    time: "15:00 인수",
    address: "제주시 용문로 64",
    mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
  },
  stay: {
    name: "제주 뜨리바다",
    nights: 5,
    address: "서귀포시 남원읍 태위로510번길 31-16",
    mapUrl: "https://map.kakao.com/link/search/제주%20뜨리바다",
  },
  mapLinks: {
    kakao: { label: "카카오맵 (전체)", url: "https://kko.to/dVTagxHHZX" },
    naverFood: { label: "네이버 먹거리", url: "https://naver.me/5wrj0ShJ" },
    naverPlay: { label: "네이버 놀거리", url: "https://naver.me/Gi0OR11p" },
    naverDessert: { label: "네이버 디저트", url: "https://naver.me/GahyuPIM" },
  },
};

const DAYS = [
  {
    id: "day1",
    label: "Day 1",
    date: "7/8 (수)",
    theme: "도착 · 아베베 · 숙소",
    summary: "공항 도착 → 렌트카 → 아베베 베이커리 → 숙소 체크인",
    swim: false,
    stops: [
      {
        time: "13:45",
        name: "제주공항 도착",
        type: "이동",
        note: "김포 13:45 출발편",
        source: null,
      },
      {
        time: "15:00",
        name: "제주OK렌터카",
        type: "렌트카",
        address: "제주시 용문로 64",
        note: "공항 셔틀 약 10~15분 간격",
        mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
        source: null,
      },
      {
        time: "16:00",
        name: "아베베 베이커리 제주",
        type: "디저트",
        address: "제주시 일도일동 1136-2",
        note: "필수 방문! 오픈 시간 확인 후 방문",
        highlight: true,
        mapUrl: "https://map.naver.com/v5/search/아베베%20베이커리%20제주",
        source: "naver",
      },
      {
        time: "17:30",
        name: "제주 뜨리바다",
        type: "숙소",
        address: "서귀포시 남원읍 태위로510번길 31-16",
        note: "5박 숙박 · 체크인",
        mapUrl: "https://map.kakao.com/link/search/제주%20뜨리바다",
        source: null,
      },
      {
        time: "19:00",
        name: "어등포해녀촌",
        type: "먹거리",
        address: "제주시 이도일동 1782-1",
        note: "가볍게 저녁 · 해녀 음식",
        mapUrl: "https://map.naver.com/v5/search/어등포해녀촌",
        source: "naver",
      },
    ],
  },
  {
    id: "day2",
    label: "Day 2",
    date: "7/9 (목)",
    theme: "북동 · 함덕 · 조천",
    summary: "함덕 수영 → 델문도 · 만춘서점 → 통일가든",
    swim: true,
    swimSpot: "함덕해수욕장",
    stops: [
      {
        time: "09:30",
        name: "함덕해수욕장",
        type: "수영",
        address: "제주시 조천읍 함덕리",
        note: "수영 1회차 · 샤워실 이용",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/함덕해수욕장",
        source: "naver",
      },
      {
        time: "11:30",
        name: "델문도",
        type: "카페",
        address: "조천읍 조함해안로 519-10",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/델문도%20제주",
        source: "kakao",
      },
      {
        time: "12:30",
        name: "만춘서점",
        type: "놀거리",
        address: "조천읍 함덕로 9",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/만춘서점%20제주",
        source: "kakao",
      },
      {
        time: "13:30",
        name: "통일가든",
        type: "먹거리",
        address: "조천읍 조와로 14",
        note: "네이버·카카오 공통",
        mapUrl: "https://map.kakao.com/link/search/통일가든%20제주",
        source: "both",
      },
      {
        time: "15:00",
        name: "글로시말차",
        type: "디저트",
        address: "조천읍 조함해안로 112",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/글로시말차",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "관곶",
        type: "놀거리",
        address: "조천읍 조함해안로 217-1",
        note: "해안 산책",
        mapUrl: "https://map.kakao.com/link/search/관곶",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "로미뮤직하우스",
        type: "놀거리",
        address: "조천읍 선교로 106",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/로미뮤직하우스",
        source: "kakao",
      },
      {
        time: "19:00",
        name: "풍림다방 커피로스터즈 송당",
        type: "디저트",
        address: "구좌읍 송당리 1377-1",
        note: "네이버 디저트",
        mapUrl: "https://map.naver.com/v5/search/풍림다방%20송당",
        source: "naver",
      },
    ],
  },
  {
    id: "day3",
    label: "Day 3",
    date: "7/10 (금)",
    theme: "동부 · 성산 · 세기알",
    summary: "세기알 수영 → 성산 일대 맛집",
    swim: true,
    swimSpot: "세기알해변",
    stops: [
      {
        time: "09:30",
        name: "세기알해변",
        type: "수영",
        address: "제주시 구좌읍",
        note: "수영 2회차 · 에메랄드빛 바다",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/세기알해변",
        source: "naver",
      },
      {
        time: "11:30",
        name: "몰마농 그대와함께 해물라면 성산본점",
        type: "먹거리",
        address: "성산 일대",
        note: "네이버 먹거리",
        mapUrl: "https://map.naver.com/v5/search/몰마농%20해물라면%20성산",
        source: "naver",
      },
      {
        time: "13:00",
        name: "회심",
        type: "먹거리",
        address: "제주시 아봉로 200",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/회심%20제주",
        source: "kakao",
      },
      {
        time: "14:30",
        name: "바라나시책골목",
        type: "놀거리",
        address: "조천읍 일주동로 952-5",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/바라나시책골목",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "5L2F",
        type: "카페",
        address: "조천읍 와흘상길 30",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/5L2F%20제주",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "시타북바 세화해변",
        type: "디저트",
        address: "구좌읍 평대리 3350-13",
        note: "북카페 · 네이버 디저트",
        mapUrl: "https://map.naver.com/v5/search/시타북바%20세화해변",
        source: "naver",
      },
      {
        time: "19:00",
        name: "복자씨연탄구이",
        type: "먹거리",
        address: "성산 일대",
        note: "네이버 먹거리",
        mapUrl: "https://map.naver.com/v5/search/복자씨연탄구이%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day4",
    label: "Day 4",
    date: "7/11 (토)",
    theme: "서부 · 판포 · 한림",
    summary: "판포 수영 → 코삿호다 · 우무 · 행원해변",
    swim: true,
    swimSpot: "판포포구 · 행원해변",
    stops: [
      {
        time: "09:30",
        name: "판포포구",
        type: "수영",
        address: "한경면 판포리",
        note: "수영 3회차 · 포구 산책",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/판포포구",
        source: "kakao",
      },
      {
        time: "11:00",
        name: "코삿호다",
        type: "디저트",
        address: "한경면 판포리 2881-3",
        note: "네이버·카카오 공통",
        mapUrl: "https://map.kakao.com/link/search/코삿호다",
        source: "both",
      },
      {
        time: "13:00",
        name: "우무",
        type: "디저트",
        address: "한림읍 옹포리 324-3",
        note: "네이버 디저트 · 한림 카페",
        mapUrl: "https://map.naver.com/v5/search/우무%20제주",
        source: "naver",
      },
      {
        time: "14:30",
        name: "KT한림빌딩",
        type: "놀거리",
        address: "한림읍 한림로 630",
        note: "카카오맵 저장 · 한림 카페거리",
        mapUrl: "https://map.kakao.com/link/search/KT한림빌딩",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "행원해변",
        type: "수영",
        address: "구좌읍 행원리 575-6",
        note: "보너스 수영 · 카카오맵",
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/행원해변",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "구씨커피로스터스",
        type: "카페",
        address: "구좌읍 구좌로 21",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/구씨커피로스터스",
        source: "kakao",
      },
      {
        time: "19:00",
        name: "미노아",
        type: "먹거리",
        address: "구좌 일대",
        note: "네이버 먹거리",
        mapUrl: "https://map.naver.com/v5/search/미노아%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day5",
    label: "Day 5",
    date: "7/12 (일)",
    theme: "남부 · 서귀포",
    summary: "남서 해안 · 서귀포 시장 · 빈티지농장",
    swim: false,
    stops: [
      {
        time: "10:00",
        name: "미영이네",
        type: "먹거리",
        address: "서귀포시 대정읍 하모리 770-29",
        note: "생선회 · 네이버 먹거리",
        mapUrl: "https://map.naver.com/v5/search/미영이네%20제주",
        source: "naver",
      },
      {
        time: "12:00",
        name: "와토커피",
        type: "카페",
        address: "서귀포시 대정읍 동일하모로 238",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/와토커피",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "번네식당",
        type: "먹거리",
        address: "서귀포시 안덕면 일주서로 1606-10",
        note: "갈치조림 · 카카오맵",
        mapUrl: "https://map.kakao.com/link/search/번네식당",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "서귀포매일올레시장",
        type: "놀거리",
        address: "서귀포시",
        note: "네이버 먹거리 · 시장 구경",
        mapUrl: "https://map.naver.com/v5/search/서귀포매일올레시장",
        source: "naver",
      },
      {
        time: "17:30",
        name: "빈티지농장",
        type: "놀거리",
        address: "서귀포시 서호동 1476-1",
        note: "네이버 놀거리 · 구제샵",
        mapUrl: "https://map.naver.com/v5/search/빈티지농장%20제주",
        source: "naver",
      },
      {
        time: "19:00",
        name: "앙프르",
        type: "먹거리",
        address: "서귀포시",
        note: "중화요리 · 네이버 먹거리",
        mapUrl: "https://map.naver.com/v5/search/앙프르%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day6",
    label: "Day 6",
    date: "7/13 (월)",
    theme: "귀국 · 제주시",
    summary: "제주시 맛집 → 렌트카 반납 → 20:50 출발",
    swim: false,
    stops: [
      {
        time: "10:00",
        name: "숙성도 제주본점",
        type: "먹거리",
        address: "제주시",
        note: "네이버 먹거리 · 점심",
        mapUrl: "https://map.naver.com/v5/search/숙성도%20제주본점",
        source: "naver",
      },
      {
        time: "12:00",
        name: "오병장 본점",
        type: "먹거리",
        address: "제주시 벌랑길 8",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/오병장%20본점",
        source: "kakao",
      },
      {
        time: "13:30",
        name: "매우릉쭈꾸미",
        type: "먹거리",
        address: "조천읍 함덕16길 11",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/매우릉쭈꾸미",
        source: "kakao",
      },
      {
        time: "15:00",
        name: "그옛맛",
        type: "먹거리",
        address: "제주시 서사로24길 12",
        note: "카카오맵 저장",
        mapUrl: "https://map.kakao.com/link/search/그옛맛%20제주",
        source: "kakao",
      },
      {
        time: "16:30",
        name: "도두슈퍼마켓",
        type: "놀거리",
        address: "제주시 서해안로 135",
        note: "카카오맵 저장 · 기념품",
        mapUrl: "https://map.kakao.com/link/search/도두슈퍼마켓",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "제주OK렌터카 반납",
        type: "렌트카",
        address: "제주시 용문로 64",
        note: "셔틀버스로 공항 이동",
        mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
        source: null,
      },
      {
        time: "20:50",
        name: "제주공항 출발",
        type: "이동",
        note: "제주 → 김포",
        source: null,
      },
    ],
  },
];

const KAKAO_JEJU_PLACES = [
  { name: "회심", area: "제주시", source: "kakao" },
  { name: "관곶", area: "조천읍", source: "kakao" },
  { name: "로미뮤직하우스", area: "조천읍", source: "kakao" },
  { name: "글로시말차", area: "조천읍", source: "kakao" },
  { name: "그옛맛", area: "제주시", source: "kakao" },
  { name: "5L2F", area: "조천읍", source: "kakao" },
  { name: "와토커피", area: "대정읍", source: "kakao" },
  { name: "구씨커피로스터스", area: "구좌읍", source: "kakao" },
  { name: "매우릉쭈꾸미", area: "조천읍", source: "kakao" },
  { name: "오병장 본점", area: "제주시", source: "kakao" },
  { name: "번네식당", area: "안덕면", source: "kakao" },
  { name: "행원해변", area: "구좌읍", source: "kakao" },
  { name: "코삿호다", area: "한경면", source: "kakao" },
  { name: "판포포구", area: "한경면", source: "kakao" },
  { name: "통일가든", area: "조천읍", source: "kakao" },
  { name: "바라나시책골목", area: "조천읍", source: "kakao" },
  { name: "KT한림빌딩", area: "한림읍", source: "kakao" },
  { name: "델문도", area: "조천읍", source: "kakao" },
  { name: "만춘서점", area: "조천읍", source: "kakao" },
  { name: "도두슈퍼마켓", area: "제주시", source: "kakao" },
];

const EXTRA_NAVER_FOOD = [
  "동복리 해녀촌", "몽탄 제주점", "월정리 호랑이네", "해맞이쉼터",
  "목장카페 밭디", "충희요리",
];
