const TRIP = {
  title: "제주 여행 코스",
  dates: "2026.7.8 (수) ~ 7.13 (월)",
  flight: {
    outbound: { date: "7/8 (수)", time: "13:45", route: "김포 → 제주" },
    inbound: { date: "7/13 (월)", time: "20:50", route: "제주 → 김포" },
  },
  rental: {
    name: "제주OK렌터카",
    time: "15:00 인수",
    address: "제주시 용문로 64",
    mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
  },
  stay: {
    name: "제주 뜨리바다",
    nights: 5,
    address: "서귀포시 남원읍 태위로510번길 31-16",
    mapUrl: "https://map.kakao.com/link/search/제주%20뜨리바다",
  },
  mapLinks: {
    kakao: { label: "카카오맵 (전체)", url: "https://kko.to/dVTagxHHZX" },
    naverFood: { label: "네이버 먹거리", url: "https://naver.me/5wrj0ShJ" },
    naverPlay: { label: "네이버 놀거리", url: "https://naver.me/Gi0OR11p" },
    naverDessert: { label: "네이버 디저트", url: "https://naver.me/GahyuPIM" },
  },
  mapImport: {
    kakao: {
      folderId: "10903649",
      folderUrl:
        "https://map.kakao.com/?map_type=TYPE_MAP&folderid=10903649&target=other&page=bookmark",
    },
    naver: [
      {
        key: "food",
        label: "먹거리",
        url: "https://naver.me/5wrj0ShJ",
        shareId: "7ca97761605e46a18b844e030b6039a3",
      },
      {
        key: "play",
        label: "놀거리",
        url: "https://naver.me/Gi0OR11p",
        shareId: "371240aaf2d34514abe4183435f83726",
      },
      {
        key: "dessert",
        label: "디저트",
        url: "https://naver.me/GahyuPIM",
        shareId: "9244aee2bd4d423e86d9cf0af5e34744",
      },
    ],
  },
};

const DEFAULT_DAYS = [
  {
    id: "day1",
    label: "Day 1",
    date: "7/8 (수)",
    theme: "도착 · 자매국수 · 아베베 · 미영이네",
    summary: "렌트 인수 → 자매국수 → 아베베 → 체크인 → 미영이네 저녁+술",
    swim: false,
    stops: [
      {
        time: "13:45",
        name: "제주공항 도착",
        type: "이동",
        note: "김포 13:45 출발편",
        source: null,
      },
      {
        time: "15:00",
        name: "제주OK렌터카",
        type: "렌트카",
        address: "제주시 용문로 64",
        note: "공항 셔틀 약 10~15분 간격",
        mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
        source: null,
      },
      {
        time: "15:30",
        name: "제주 자매국수",
        type: "먹거리",
        address: "제주시 일도이동 1055-3",
        note: "점심 · 필수! 고기국수",
        highlight: true,
        mapUrl: "https://map.naver.com/v5/search/제주%20자매국수",
        source: "naver",
      },
      {
        time: "16:15",
        name: "아베베 베이커리 제주",
        type: "디저트",
        address: "제주시 일도일동 1136-2",
        note: "필수 방문! 오픈·휴무 시간 확인",
        highlight: true,
        mapUrl: "https://map.naver.com/v5/search/아베베%20베이커리%20제주",
        source: "naver",
      },
      {
        time: "17:30",
        name: "제주 뜨리바다",
        type: "숙소",
        address: "서귀포시 남원읍 태위로510번길 31-16",
        note: "5박 숙박 · 체크인 · 잠깐 쉬기",
        mapUrl: "https://map.kakao.com/link/search/제주%20뜨리바다",
        source: null,
      },
      {
        time: "19:00",
        name: "미영이네",
        type: "먹거리",
        address: "서귀포시 대정읍 하모리 770-29",
        note: "저녁 · 고등어회+쏘주 · 일요일 점심 대신 저녁으로!",
        highlight: true,
        mapUrl: "https://map.naver.com/v5/search/미영이네%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day2",
    label: "Day 2",
    date: "7/9 (목)",
    theme: "북동 · 함덕 · 조천 · 로미",
    summary: "수영 → 정리 → 점심 → 북카페 → 카페 → 로미 → 저녁 → 일몰 → 글로시(18:30 LO)",
    swim: true,
    swimSpot: "함덕해수욕장",
    stops: [
      {
        time: "09:30",
        name: "함덕해수욕장",
        type: "수영",
        address: "제주시 조천읍 함덕리",
        note: "아침 수영",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/함덕해수욕장",
        source: "naver",
      },
      {
        time: "10:30",
        name: "수영 후 정리",
        type: "이동",
        address: "함덕 인근",
        note: "샤워 · 옷 갈아입기 · 수건 정리",
        source: null,
      },
      {
        time: "12:00",
        name: "통일가든",
        type: "먹거리",
        address: "조천읍 조와로 14",
        note: "점심(12) · 영업시간 확인",
        mapUrl: "https://map.kakao.com/link/search/통일가든%20제주",
        source: "both",
      },
      {
        time: "13:00",
        name: "만춘서점",
        type: "놀거리",
        address: "조천읍 함덕로 9",
        note: "함덕 독립서점",
        mapUrl: "https://map.kakao.com/link/search/만춘서점%20제주",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "바라나시책골목",
        type: "놀거리",
        address: "조천읍 일주동로 952-5",
        note: "함덕·조천 일대 북카페",
        mapUrl: "https://map.kakao.com/link/search/바라나시책골목",
        source: "kakao",
      },
      {
        time: "15:00",
        name: "델문도",
        type: "카페",
        address: "조천읍 조함해안로 519-10",
        note: "카페(1회차)",
        mapUrl: "https://map.kakao.com/link/search/델문도%20제주",
        source: "kakao",
      },
      {
        time: "15:45",
        name: "로미뮤직하우스",
        type: "카페",
        address: "조천읍 조함해안로 217",
        note: "음악+카페 · 조천 해안",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/로미뮤직하우스",
        source: "kakao",
      },
      {
        time: "16:30",
        name: "매우릉쭈꾸미",
        type: "먹거리",
        address: "조천읍 함덕16길 11",
        note: "저녁(16) · 영업시간 확인",
        mapUrl: "https://map.kakao.com/link/search/매우릉쭈꾸미",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "관곶",
        type: "놀거리",
        address: "조천읍 조함해안로 217-1",
        note: "해안 산책 · 일몰",
        mapUrl: "https://map.kakao.com/link/search/관곶",
        source: "kakao",
      },
      {
        time: "18:15",
        name: "글로시말차",
        type: "디저트",
        address: "조천읍 조함해안로 112",
        note: "라스트오더 18:30 · 반드시 이전 도착!",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/글로시말차",
        source: "kakao",
      },
    ],
  },
  {
    id: "day3",
    label: "Day 3",
    date: "7/10 (금)",
    theme: "동부 · 행원수영 · 성산 · 섭지",
    summary: "행원 아침수영 → 동부 점심 → 섭지·성산 → 저녁 → 해녀촌",
    swim: true,
    swimSpot: "행원해변",
    stops: [
      {
        time: "09:30",
        name: "행원해변",
        type: "수영",
        address: "구좌읍 행원리",
        note: "아침 수영 · 물때·날씨 확인",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/행원해변",
        source: "kakao",
      },
      {
        time: "10:30",
        name: "수영 후 정리",
        type: "이동",
        address: "행원해변 인근",
        note: "샤워 · 옷 갈아입기",
        source: null,
      },
      {
        time: "12:00",
        name: "몰마농 그대와함께 해물라면 성산본점",
        type: "먹거리",
        address: "성산 일대",
        note: "점심(12)",
        mapUrl: "https://map.naver.com/v5/search/몰마농%20해물라면%20성산",
        source: "naver",
      },
      {
        time: "13:30",
        name: "섭지코지",
        type: "놀거리",
        address: "성산읍 섭지코지로",
        note: "해안 절경 · 산책",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/섭지코지",
        source: "kakao",
      },
      {
        time: "14:30",
        name: "시타북바 세화해변",
        type: "디저트",
        address: "구좌읍 평대리 3350-13",
        note: "디저트/북카페",
        mapUrl: "https://map.naver.com/v5/search/시타북바%20세화해변",
        source: "naver",
      },
      {
        time: "15:30",
        name: "구씨커피로스터스",
        type: "카페",
        address: "구좌읍 구좌로 21",
        note: "카페 · 세화·평대 일대",
        mapUrl: "https://map.kakao.com/link/search/구씨커피로스터스",
        source: "kakao",
      },
      {
        time: "16:30",
        name: "복자씨연탄구이",
        type: "먹거리",
        address: "성산 일대",
        note: "저녁(16) · 영업시간 확인",
        mapUrl: "https://map.naver.com/v5/search/복자씨연탄구이%20제주",
        source: "naver",
      },
      {
        time: "17:30",
        name: "성산일출봉",
        type: "놀거리",
        address: "성산읍 성산리",
        note: "일출봉 전망 · 입장시간·휴무 확인",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/성산일출봉",
        source: "kakao",
      },
      {
        time: "18:30",
        name: "샤이니숲길",
        type: "놀거리",
        address: "구좌읍",
        note: "숲길 산책 · 해 질 무렵",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/샤이니숲길%20제주",
        source: "kakao",
      },
      {
        time: "20:00",
        name: "동복리 해녀촌",
        type: "먹거리",
        address: "구좌읍",
        note: "저녁 식사 · 구좌 동선",
        mapUrl: "https://map.naver.com/v5/search/동복리%20해녀촌%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day4",
    label: "Day 4",
    date: "7/11 (토)",
    theme: "서부 · 판포 · 한림 · 목장",
    summary: "판포 수영 → 번네 점심 → 길갈·목장랜드 → 카페 → 저녁",
    swim: true,
    swimSpot: "판포포구",
    stops: [
      {
        time: "09:30",
        name: "판포포구",
        type: "수영",
        address: "한경면 판포리",
        note: "아침 수영",
        highlight: true,
        swim: true,
        mapUrl: "https://map.kakao.com/link/search/판포포구",
        source: "kakao",
      },
      {
        time: "10:30",
        name: "수영 후 정리",
        type: "이동",
        address: "판포 인근",
        note: "샤워 · 옷 갈아입기",
        source: null,
      },
      {
        time: "12:00",
        name: "번네식당",
        type: "먹거리",
        address: "안덕면 일주서로 1606-10",
        note: "점심(12) · 수영 후 바로 이동",
        mapUrl: "https://map.kakao.com/link/search/번네식당",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "길갈팜랜드",
        type: "놀거리",
        address: "한경면",
        note: "오후 놀거리 · 영업시간 확인",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/길갈팜랜드",
        source: "kakao",
      },
      {
        time: "15:30",
        name: "제주목장랜드",
        type: "놀거리",
        address: "한경면",
        note: "목장 체험 · 오후",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/제주목장랜드",
        source: "kakao",
      },
      {
        time: "16:30",
        name: "우무",
        type: "디저트",
        address: "한림읍 옹포리 324-3",
        note: "디저트 · 한림",
        mapUrl: "https://map.naver.com/v5/search/우무%20제주",
        source: "naver",
      },
      {
        time: "17:15",
        name: "5L2F",
        type: "카페",
        address: "한림읍",
        note: "카페 · 한림 일대",
        mapUrl: "https://map.kakao.com/link/search/5L2F%20제주",
        source: "kakao",
      },
      {
        time: "18:30",
        name: "오병장 본점",
        type: "먹거리",
        address: "제주시 벌랑길 8",
        note: "저녁 · 숙소 방향 경유",
        mapUrl: "https://map.kakao.com/link/search/오병장%20본점",
        source: "kakao",
      },
      {
        time: "20:00",
        name: "숙성도 제주본점",
        type: "먹거리",
        address: "제주시",
        note: "늦은 저녁 · 제주시 귀숙",
        mapUrl: "https://map.naver.com/v5/search/숙성도%20제주본점",
        source: "naver",
      },
    ],
  },
  {
    id: "day5",
    label: "Day 5",
    date: "7/12 (일)",
    theme: "남부 · 서귀포 · 서우봉",
    summary: "올레시장 → 놀거리 → 서우봉 → 카페 → 저녁",
    swim: false,
    stops: [
      {
        time: "11:00",
        name: "서귀포매일올레시장",
        type: "먹거리",
        address: "서귀포시",
        note: "점심 · 시장 구경",
        mapUrl: "https://map.naver.com/v5/search/서귀포매일올레시장",
        source: "naver",
      },
      {
        time: "12:30",
        name: "오늘도일기",
        type: "놀거리",
        address: "서귀포시",
        note: "소품샵 · 서귀포",
        mapUrl: "https://map.naver.com/v5/search/오늘도일기%20서귀포",
        source: "naver",
      },
      {
        time: "13:30",
        name: "빈티지농장",
        type: "놀거리",
        address: "서귀포시",
        note: "네이버 놀거리",
        mapUrl: "https://map.naver.com/v5/search/빈티지농장%20제주",
        source: "naver",
      },
      {
        time: "15:00",
        name: "돌문화공원",
        type: "놀거리",
        address: "서귀포시",
        note: "돌하르방 공원 · 산책",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/돌문화공원",
        source: "kakao",
      },
      {
        time: "16:00",
        name: "서우봉",
        type: "놀거리",
        address: "서귀포시",
        note: "오름 트레킹 · 일몰 전",
        highlight: true,
        mapUrl: "https://map.kakao.com/link/search/서우봉%20제주",
        source: "kakao",
      },
      {
        time: "17:30",
        name: "와토커피",
        type: "카페",
        address: "서귀포시 대정읍 동일하모로 238",
        note: "카페(1회차)",
        mapUrl: "https://map.kakao.com/link/search/와토커피",
        source: "kakao",
      },
      {
        time: "18:30",
        name: "앙프르",
        type: "먹거리",
        address: "서귀포시",
        note: "저녁(18)",
        mapUrl: "https://map.naver.com/v5/search/앙프르%20제주",
        source: "naver",
      },
      {
        time: "19:30",
        name: "목장카페 밭디",
        type: "카페",
        address: "제주",
        note: "카페(2회차)",
        mapUrl: "https://map.naver.com/v5/search/목장카페%20밭디%20제주",
        source: "naver",
      },
      {
        time: "20:30",
        name: "충희요리",
        type: "먹거리",
        address: "제주",
        note: "늦은 저녁",
        mapUrl: "https://map.naver.com/v5/search/충희요리%20제주",
        source: "naver",
      },
    ],
  },
  {
    id: "day6",
    label: "Day 6",
    date: "7/13 (월)",
    theme: "귀국 · 제주시",
    summary: "점심(12) → 회심 → 카페 → 저녁 → 반납 → 공항",
    swim: false,
    stops: [
      {
        time: "12:00",
        name: "그옛맛",
        type: "먹거리",
        address: "제주시 서사로24길 12",
        note: "점심(12)",
        mapUrl: "https://map.kakao.com/link/search/그옛맛%20제주",
        source: "kakao",
      },
      {
        time: "14:00",
        name: "회심",
        type: "먹거리",
        address: "제주시 아봉로 200",
        note: "일식 소바 · 17시 마감",
        mapUrl: "https://map.kakao.com/link/search/회심%20제주",
        source: "kakao",
      },
      {
        time: "15:30",
        name: "풍림다방 커피로스터즈 송당",
        type: "카페",
        address: "제주시",
        note: "카페 · 공항 방향",
        mapUrl: "https://map.naver.com/v5/search/풍림다방%20송당",
        source: "naver",
      },
      {
        time: "16:30",
        name: "몽탄 제주점",
        type: "먹거리",
        address: "제주",
        note: "저녁(16)",
        mapUrl: "https://map.naver.com/v5/search/몽탄%20제주점%20제주",
        source: "naver",
      },
      {
        time: "19:30",
        name: "제주OK렌터카 반납",
        type: "렌트카",
        address: "제주시 용문로 64",
        note: "셔틀버스로 공항 이동",
        mapUrl: "https://map.kakao.com/link/search/제주OK렌터카",
        source: null,
      },
      {
        time: "20:50",
        name: "제주공항 출발",
        type: "이동",
        note: "제주 → 김포",
        source: null,
      },
    ],
  },
];

const KAKAO_JEJU_PLACES = [
  { name: "회심", area: "제주시", source: "kakao" },
  { name: "관곶", area: "조천읍", source: "kakao" },
  { name: "로미뮤직하우스", area: "조천읍", source: "kakao" },
  { name: "글로시말차", area: "조천읍", source: "kakao" },
  { name: "그옛맛", area: "제주시", source: "kakao" },
  { name: "5L2F", area: "한림읍", source: "kakao" },
  { name: "와토커피", area: "대정읍", source: "kakao" },
  { name: "구씨커피로스터스", area: "구좌읍", source: "kakao" },
  { name: "매우릉쭈꾸미", area: "조천읍", source: "kakao" },
  { name: "오병장 본점", area: "제주시", source: "kakao" },
  { name: "번네식당", area: "안덕면", source: "kakao" },
  { name: "행원해변", area: "구좌읍", source: "kakao" },
  { name: "판포포구", area: "한경면", source: "kakao" },
  { name: "통일가든", area: "조천읍", source: "kakao" },
  { name: "바라나시책골목", area: "조천읍", source: "kakao" },
  { name: "델문도", area: "조천읍", source: "kakao" },
  { name: "만춘서점", area: "조천읍", source: "kakao" },
  { name: "섭지코지", area: "성산읍", source: "kakao" },
  { name: "성산일출봉", area: "성산읍", source: "kakao" },
  { name: "샤이니숲길", area: "구좌읍", source: "kakao" },
  { name: "길갈팜랜드", area: "한경면", source: "kakao" },
  { name: "제주목장랜드", area: "한경면", source: "kakao" },
  { name: "서우봉", area: "서귀포시", source: "kakao" },
  { name: "돌문화공원", area: "서귀포시", source: "kakao" },
];

const NAVER_SAVED_PLACES = [
  { name: "미영이네", folder: "먹거리" },
  { name: "제주 자매국수", folder: "먹거리" },
  { name: "통일가든", folder: "먹거리" },
  { name: "어등포해녀촌", folder: "먹거리" },
  { name: "숙성도 제주본점", folder: "먹거리" },
  { name: "함덕해수욕장", folder: "먹거리" },
  { name: "몰마농 그대와함께 해물라면 성산본점", folder: "먹거리" },
  { name: "동복리 해녀촌", folder: "먹거리" },
  { name: "앙프르", folder: "먹거리" },
  { name: "복자씨연탄구이", folder: "먹거리" },
  { name: "충희요리", folder: "먹거리" },
  { name: "몽탄 제주점", folder: "먹거리" },
  { name: "월정리 호랑이네", folder: "먹거리" },
  { name: "미노아", folder: "먹거리" },
  { name: "서귀포매일올레시장", folder: "먹거리" },
  { name: "빈티지농장", folder: "놀거리" },
  { name: "오늘도일기", folder: "놀거리" },
  { name: "아베베 베이커리 제주", folder: "디저트" },
  { name: "시타북바 세화해변", folder: "디저트" },
  { name: "풍림다방 커피로스터즈 송당", folder: "디저트" },
  { name: "우무", folder: "디저트" },
];

const STOP_TYPES = ["이동", "렌트카", "숙소", "먹거리", "디저트", "카페", "놀거리", "수영"];

let DAYS = DEFAULT_DAYS;

function isPlaceScheduled(placeName, days) {
  const targetDays = days || DAYS;
  return targetDays.some((day) =>
    day.stops.some((stop) => {
      if (stop.name === placeName) return true;
      return (
        stop.name.includes(placeName) ||
        placeName.includes(stop.name)
      );
    })
  );
}

function getKakaoPlacesList() {
  if (typeof TripStorage !== "undefined" && TripStorage.getKakaoPlaces) {
    return TripStorage.getKakaoPlaces();
  }
  return KAKAO_JEJU_PLACES;
}

function getNaverPlacesList() {
  if (typeof TripStorage !== "undefined" && TripStorage.getNaverPlaces) {
    return TripStorage.getNaverPlaces();
  }
  return NAVER_SAVED_PLACES;
}

function getUnassignedNaverPlaces() {
  return getNaverPlacesList().filter((p) => !isPlaceScheduled(p.name));
}

function getUnassignedKakaoPlaces() {
  return getKakaoPlacesList().filter((p) => !isPlaceScheduled(p.name));
}
